### ISSUE TITLE
Unknown format error in driver log when sendTo() function calling

### ISSUE THREAD

**Issue by asutpshnik** [iobroker-community-adapters/ioBroker.places#14]
Adapter settings:
![image](https://user-images.githubusercontent.com/60661789/90336652-e6265c80-dfe5-11ea-8355-4b706066fa80.png)
![image](https://user-images.githubusercontent.com/60661789/90336657-f1798800-dfe5-11ea-909c-9c94944d7f3a.png)
![image](https://user-images.githubusercontent.com/60661789/90336666-fcccb380-dfe5-11ea-86d0-54992cf5cb22.png)

I use this script in js-driver for example:
```
sendTo('places.0', {
        user:       "Andrew",
        latitude:   55.754119,
        longitude:  37.620229,
        elevation:  100,
        timestamp:  1597587966
});
```

When run script, adapter places.0 stopped with error in log:
![image](https://user-images.githubusercontent.com/60661789/90336784-c6436880-dfe6-11ea-8862-d2b22e2ebab4.png)

**Comment by GermanBluefox** [comment]
PLease check 1.0.0

**Comment by asutpshnik** [comment]
> PLease check 1.0.0

Working!
