### ISSUE TITLE
feature request: traccar

### ISSUE THREAD

**Issue by Wildshunter** [iobroker-community-adapters/ioBroker.places#15]
thanks for your wonderful adapter!
Please could you implement a traccar interface to get data from traccar server? https://www.traccar.org/server/
thanks

**Comment by BasGo** [comment]
Hi Wildshunter,

it would be possible, of course. Unfortunately I haven't got neither a traccar server nor a traccar client, so it would be much work to implement their API. Because of this it's not possible to build up an integration, I'm sorry :-(

Isn't there another way that a traccar server can call an URL with usable data?

Best regards

Bastian

**Comment by Wildshunter** [comment]
Hi Bastian, thanks, yes, but I am not so comfortable with Blocky or Parser.... I cannot pick out the right information for deviceID, longitude and latitude and create an usable object in iobroker....
via api url i.e. http://admin:test@192.168.0.12:8082/api/positions it shows i.e.
usable data like this i.e: 
----
[{"id":53111,"attributes":{"batteryLevel":58.0,"distance":94.65,"totalDistance":1344868.24,"motion":false},"deviceId":1,"type":null,"protocol":"osmand","serverTime":"2020-04-17T18:35:00.438+0000","deviceTime":"2020-04-17T18:34:57.000+0000","fixTime":"2020-04-17T18:34:57.000+0000","outdated":false,"valid":true,"latitude":12.345678,"longitude":1.234567,"altitude":0.0,"speed":0.0,"course":0.0,"address":null,"accuracy":899.9990234375,"network":null},{"id":284460,"attributes":{"batteryLevel":83.0,"distance":0.72,"totalDistance":4321818.69,"motion":false},"deviceId":2,"type":null,"protocol":"osmand","serverTime":"2020-08-20T12:35:30.941+0000","deviceTime":"2020-08-20T12:35:29.000+0000","fixTime":"2020-08-20T12:35:29.000+0000","outdated":false,"valid":true,"latitude":12.34567,"longitude":1.234567,"altitude":0.0,"speed":0.0,"course":0.0,"address":null,"accuracy":32.0989990234375,"network":null},{"id":284469,"attributes":{"batteryLevel":79.0,"distance":253.0,"totalDistance":7731843.67,"motion":false},"deviceId":3,"type":null,"protocol":"osmand","serverTime":"2020-08-20T12:41:24.369+0000","deviceTime":"2020-08-20T12:41:21.000+0000","fixTime":"2020-08-20T12:41:21.000+0000","outdated":false,"valid":true,"latitude":12.345678,"longitude":12.123455,"altitude":320.70001220703125,"speed":0.0,"course":0.0,"address":null,"accuracy":13.118000030517578,"network":null},{"id":284463,"attributes":{"batteryLevel":89.0,"distance":0.39,"totalDistance":2992001.15,"motion":false},"deviceId":4,"type":null,"protocol":"osmand","serverTime":"2020-08-20T12:36:57.445+0000","deviceTime":"2020-08-20T12:36:57.000+0000","fixTime":"2020-08-20T12:36:57.000+0000","outdated":false,"valid":true,"latitude":12.34567,"longitude":12.345673,"altitude":120.70001220703125,"speed":0.0,"course":0.0,"address":null,"accuracy":13.961000442504883,"network":null},
-----
