### ISSUE TITLE
error status 200

### ISSUE THREAD

**Issue by lobomau76** [iobroker-community-adapters/ioBroker.places#17]
Since today I have the following error in the places Adapter. Do you know what it means?
The Google Maps API key seems to be valid.

`

places.0 | 2020-11-11 09:43:14.210 | error | (26587) Error while requesting route: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:43:14 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1990
-- | -- | -- | --
places.0 | 2020-11-11 09:43:14.127 | error | (26587) Error while requesting elevation: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:43:14 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1
places.0 | 2020-11-11 09:43:14.041 | error | (26587) Error while requesting address: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:43:14 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 199
places.0 | 2020-11-11 09:43:05.714 | error | (26587) Error while requesting route: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:43:05 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1990
places.0 | 2020-11-11 09:43:05.634 | error | (26587) Error while requesting elevation: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:43:05 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1
places.0 | 2020-11-11 09:43:05.551 | error | (26587) Error while requesting address: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:43:05 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 199
places.0 | 2020-11-11 09:42:58.642 | error | (26587) Error while requesting route: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:42:58 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1990
places.0 | 2020-11-11 09:42:58.549 | error | (26587) Error while requesting elevation: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 08:42:58 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1

`

**Comment by BasGo** [comment]
Do you have any additional information (f.e. the error message itself)?

**Comment by lobomau76** [comment]
Is this not the error message itself?

**Comment by BasGo** [comment]
It's just the beginning of the error message, the complete message should look like:

`Error while requesting address: {"status":200,"headers":{"content-type":"application/json; charset=UTF-8","date":"Wed, 11 Nov 2020 09:11:39 GMT","pragma":"no-cache","expires":"Fri, 01 Jan 1990 00:00:00 GMT","cache-control":"no-cache, must-revalidate","access-control-allow-origin":"*","server":"mafe","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","server-timing":"gfet4t7; dur=31","alt-svc":"h3-Q050=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","vary":"Accept-Encoding","connection":"close","transfer-encoding":"chunked"},"json":{"error_message":"This API key is not authorized to use this service or API.","results":[],"status":"REQUEST_DENIED"},"requestUrl":"https://maps.googleapis.com/maps/api/geocode/json?language=de&latlng=51.xxxxxx%2C7.xxxxxxx&key=THE_KEY","query":{"language":"de","latlng":"51.xxxxxx,7.xxxxxxx","key":"THE_KEY"}}`

**Comment by lobomau76** [comment]
Thank you. You have already helped me. Seeing the whole error message I found the concerning part:
"error_message":"You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable

I have added a second object in places. Perhaps it is too much traffic now and not for free anymore.

I will close this issue.
