### ISSUE TITLE
feature request: Presence of people in user places

### ISSUE THREAD

**Issue by 2scorpio** [iobroker-community-adapters/ioBroker.places#18]
Hello.
This is a great adapter!!!

But this functionality is very lacking.
On the Custom Location Setup page - add a check mark to the location - check for users in that location.
So that objects can see who is in this place. Similar to Home

**Comment by 2scorpio** [comment]
so that these parameters are read for each added "User Place"
places.0.anybodyAtHome
places.0.clearHome
places.0.numberAtHome
places.0.personsAtHome

can even make a separate folder where work and Scool are custom places - like so:
places.0.Circles.Home.anybodyAt
places.0.Circles.Home.clear
places.0.Circles.Home.numberAt
places.0.Circles.Home.personsAt

places.0.Circles.Work.anybodyAt
places.0.Circles.Work.clear
places.0.Circles.Work.numberAt
places.0.Circles.Work.personsAt

places.0.Circles.Scool.anybodyAt
places.0.Circles.Scool.clear
places.0.Circles.Scool.numberAt
places.0.Circles.Scool.personsAt

and then Places will be perfect

**Comment by BasGo** [comment]
This would be possible of course. I'll keep it in mind, but I cannot estimate when such a feature will be available (lack of time).
