### ISSUE TITLE
NumberAtHome and AnybodyAtHome are not updated anymore.

### ISSUE THREAD

**Issue by copystring** [iobroker-community-adapters/ioBroker.places#52]
Something is wrong here.
NumberAtHome and AnybodyAtHome are not updated anymore.
Everything is the latest version. Deleted places.0 and restarted places. NumberAtHome and AnybodyAtHome are created. Sending my current location works.
Me (Felix) is marked as home (ZuHause) but NumberAtHome stays 0 and AnybodeAtHome is false.

![image](https://user-images.githubusercontent.com/1298861/163730876-4409dd4b-c1b9-4a44-a090-aafa10ab47d6.png)

So I went back to version 1.0.0 and tested it. Works perfectly fine. Version 1.1.1 does not work.

**Comment by Apollon77** [comment]
Can you please post a debug log from both version? Maybe we can see a difference ...

**Comment by Apollon77** [comment]
Ok, not needed, I have it, fix coming

**Comment by copystring** [comment]
This works now. Thank you for the quick fix!
